[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "easy-cipher"
version = "1.0.0"
description = "Ciper tools"
requires-python = ">=3.10"

[tool.ruff]
line-length = 120
target-version = "py310"
exclude = [
    ".git", ".ruff_cache", ".mypy_cache", ".venv", "venv", "__pycache__",
]

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "N",
    "B",
    "C4",
    "UP",
]
ignore = [
    "E501",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
